[build-system]
requires = ["cibuildwheel"]

[tool.cibuildwheel]
environment = { "CGO_ENABLED" = "1" }

# Skip builds for unsupported architectures
skip = ["pp*", "*-win32", "*-manylinux_i686"]

[tool.cibuildwheel.linux]
archs = ["x86_64", "aarch64"]
before-build = "apt-get update && apt-get install -y gcc musl-dev"

[tool.cibuildwheel.macos]
archs = ["x86_64", "arm64"]
before-build = "brew install llvm"

[tool.cibuildwheel.windows]
archs = ["AMD64"]
before-build = "choco install mingw"