[tool.cibuildwheel]
environment = { "CGO_ENABLED" = "1" }
build-frontend = "pip"
skip = ["pp*", "*-win32", "*-manylinux_i686"]

[tool.cibuildwheel.linux]
archs = ["x86_64", "aarch64"]
environment = { "GOOS" = "linux", "GOARCH" = "amd64" }
before-all = """
    yum install -y gcc mingw64-gcc
    curl -sSL https://go.dev/dl/go1.22.linux-amd64.tar.gz | tar -xz -C /usr/local
    export PATH=$PATH:/usr/local/go/bin
"""

[tool.cibuildwheel.macos]
archs = ["x86_64", "arm64"]
environment = { "GOOS" = "darwin", "GOARCH" = "arm64" }
before-build = "brew install go"

[tool.cibuildwheel.windows]
archs = ["AMD64"]
environment = { "GOOS" = "windows", "GOARCH" = "amd64" }
before-build = "choco install mingw -y"